import type { ServiceProvider } from './types';

export const PROVIDERS: ServiceProvider[] = [
  {
    id: 13,
    name: 'Suresh Kumar',
    occupation: 'Plumber',
    phone: '+91 98765 11111',
    area: 'Bhagwanpur',
    imageUrl: 'https://picsum.photos/seed/suresh/400/400',
    experience: '15 years of experience',
    reviews: [
      { reviewer: 'Rakesh Rai', comment: 'Very experienced and solved a complex issue.' },
      { reviewer: 'Sunita Sharma', comment: 'Quick and reliable service.' },
    ],
  },
  {
    id: 14,
    name: 'Deepak Paswan',
    occupation: 'Electrician',
    phone: '+91 98765 22222',
    area: 'Bhagwanpur',
    imageUrl: 'https://picsum.photos/seed/deepak/400/400',
    experience: '9 years of experience',
    reviews: [
      { reviewer: 'Manoj Singh', comment: 'Professional and knew his work well.' },
      { reviewer: 'Anita Devi', comment: 'Installed all the lights perfectly.' },
    ],
  },
  {
    id: 15,
    name: 'Poonam Devi',
    occupation: 'Tailor',
    phone: '+91 98765 33333',
    area: 'Bhagwanpur',
    imageUrl: 'https://picsum.photos/seed/poonam/400/400',
    experience: '12 years of experience',
    reviews: [
      { reviewer: 'Rekha Kumari', comment: 'Excellent stitching for my blouse.' },
      { reviewer: 'Priya Sinha', comment: 'Always delivers on time with great quality.' },
    ],
  },
  {
    id: 9,
    name: 'Arjun Singh',
    occupation: 'Mechanic',
    phone: '+91 91122 33445',
    area: 'Vaishali',
    imageUrl: 'https://picsum.photos/seed/arjun/400/400',
    experience: '10 years of experience',
    reviews: [
      { reviewer: 'Krishna Kumar', comment: 'Best mechanic in town. My car runs smoothly now.' },
      { reviewer: 'Ravi Mahto', comment: 'Trustworthy and skilled.' },
    ],
  },
  {
    id: 10,
    name: 'Kavita Kumari',
    occupation: 'Tailor',
    phone: '+91 95566 77889',
    area: 'Vaishali',
    imageUrl: 'https://picsum.photos/seed/kavita/400/400',
    experience: '8 years of experience',
    reviews: [
      { reviewer: 'Sita Devi', comment: 'Perfect fitting and beautiful stitching.' },
      { reviewer: 'Geeta Sinha', comment: 'Delivered the dress on time for the function.' },
    ],
  },
  {
    id: 11,
    name: 'Rajesh Prasad',
    occupation: 'Painter',
    phone: '+91 99988 77665',
    area: 'Vaishali',
    imageUrl: 'https://picsum.photos/seed/rajesh/400/400',
    experience: '6 years of experience',
    reviews: [
      { reviewer: 'Mohan Roy', comment: 'Clean work and very reasonable price.' },
      { reviewer: 'Usha Singh', comment: 'He helped us choose the right colors. Very happy.' },
    ],
  },
  {
    id: 12,
    name: 'Raju Sharma',
    occupation: 'Electrician',
    phone: '+91 97788 66554',
    area: 'Vaishali',
    imageUrl: 'https://picsum.photos/seed/raju/400/400',
    experience: '7 years of experience',
    reviews: [
        { reviewer: 'Pankaj Tiwari', comment: 'Quick response and fixed the short circuit issue.' },
        { reviewer: 'Amit Singh', comment: 'A reliable electrician for any household work.' },
    ],
  },
  {
    id: 1,
    name: 'Rohan Sharma',
    occupation: 'Plumber',
    phone: '+91 98765 43210',
    area: 'Mumbai',
    imageUrl: 'https://picsum.photos/seed/rohan/400/400',
    experience: '8 years of experience',
    reviews: [
      { reviewer: 'Aarav Gupta', comment: 'Very professional and fixed the leak quickly!' },
      { reviewer: 'Ishaan Verma', comment: 'Polite and knowledgeable. Highly recommended.' },
    ],
  },
  {
    id: 2,
    name: 'Priya Patel',
    occupation: 'Electrician',
    phone: '+91 91234 56789',
    area: 'Delhi',
    imageUrl: 'https://picsum.photos/seed/priya/400/400',
    experience: '10 years of experience',
    reviews: [
      { reviewer: 'Aditi Singh', comment: 'Did a great job with the wiring in my new office.' },
      { reviewer: 'Riya Sharma', comment: 'Safe and efficient work. Very reliable.' },
    ],
  },
  {
    id: 3,
    name: 'Amit Kumar',
    occupation: 'Carpenter',
    phone: '+91 87654 32109',
    area: 'Bangalore',
    imageUrl: 'https://picsum.photos/seed/amit/400/400',
    experience: '12 years of experience',
    reviews: [
      { reviewer: 'Vihaan Reddy', comment: 'Beautiful custom shelves. The craftsmanship is amazing.' },
      { reviewer: 'Kabir Joshi', comment: 'Finished the work on time and was very clean.' },
    ],
  },
  {
    id: 4,
    name: 'Sunita Devi',
    occupation: 'Painter',
    phone: '+91 76543 21098',
    area: 'Chennai',
    imageUrl: 'https://picsum.photos/seed/sunita/400/400',
    experience: '7 years of experience',
    reviews: [
      { reviewer: 'Anika Nair', comment: 'The rooms look fantastic. Very neat and professional.' },
      { reviewer: 'Zara Khan', comment: 'Sunita and her team were wonderful.' },
    ],
  },
  {
    id: 5,
    name: 'Vikram Singh',
    occupation: 'AC Repair',
    phone: '+91 99887 76655',
    area: 'Hyderabad',
    imageUrl: 'https://picsum.photos/seed/vikram/400/400',
    experience: '6 years of experience',
    reviews: [
      { reviewer: 'Aryan Rao', comment: 'My AC is working like new again. Fast service!' },
      { reviewer: 'Sai Kumar', comment: 'Honest and fair pricing.' },
    ],
  },
  {
    id: 6,
    name: 'Anjali Mehta',
    occupation: 'House Cleaner',
    phone: '+91 88776 65544',
    area: 'Pune',
    imageUrl: 'https://picsum.photos/seed/anjali/400/400',
    experience: '5 years of experience',
    reviews: [
      { reviewer: 'Diya Deshpande', comment: 'My home has never been so clean. Anjali is meticulous.' },
      { reviewer: 'Myra Kulkarni', comment: 'Punctual and very thorough.' },
    ],
  },
   {
    id: 7,
    name: 'Sanjay Verma',
    occupation: 'Electrician',
    phone: '+91 93210 98765',
    area: 'Kolkata',
    imageUrl: 'https://picsum.photos/seed/sanjay/400/400',
    experience: '9 years of experience',
    reviews: [
      { reviewer: 'Arin Bose', comment: 'Solved a complex electrical issue that others couldn\'t.' },
      { reviewer: 'Ishani Das', comment: 'Very professional. Will call him again for sure.' },
    ],
  },
  {
    id: 8,
    name: 'Meera Iyer',
    occupation: 'Plumber',
    phone: '+91 98765 12345',
    area: 'Ahmedabad',
    imageUrl: 'https://picsum.photos/seed/meera/400/400',
    experience: '15 years of experience',
    reviews: [
      { reviewer: 'Advait Shah', comment: 'Meera is an expert. She fixed our pipeline perfectly.' },
      { reviewer: 'Samaira Trivedi', comment: 'Very experienced and gave good advice.' },
    ],
  },
];